export const AKWE_STARTER_TASKS: readonly string[] = [
  'Has deployed a Lambda function',
  'Uses Infrastructure as Code',
  'Has an AWS certification',
  'Has attended an AWS community event before',
  'Is at AKWE for the first time',
  'Came from outside Cebu City',
  'Can name a favorite AWS service',
  'Has built a project in a weekend',
  'Has used a container this month',
  'Has tried a new AWS service this year',
  'Has given a technical talk',
  'Has helped someone debug a problem',
  'Has joined a tech community group',
  'Has a home lab',
  'Has used AWS CDK',
  'Has used Terraform',
  'Has built an app with TypeScript',
  'Has written a CI workflow',
  'Has shipped a serverless app',
  'Has tried a generative AI tool',
  'Has connected a database to an app',
  'Can explain a cloud concept in one minute',
  'Has been to a tech meetup this month',
  'Has changed a career path',
  'Has taught a friend something technical',
  'Has a favorite terminal command',
  'Prefers building tools to meetings',
  'Has tried a new Cebuano dish this year',
  'Has a notebook of project ideas',
  'Can touch-type',
  'Uses a keyboard layout other than QWERTY',
  'Has learned from a production bug',
  'Has built a website for someone else',
  'Has paired on a tricky bug',
  'Can name a favorite open-source project',
  'Has made something just for fun',
];
