export const DEFAULT_TASK_BAG: readonly string[] = [
  'Has a pet',
  'Has traveled abroad this year',
  'Is left-handed',
  'Plays a musical instrument',
  'Speaks more than two languages',
  'Has never broken a bone',
  'Has been to Asia',
  'Loves spicy food',
  'Is an only child',
  'Has run a marathon',
  'Was born in December',
  'Has met someone famous',
  'Wears glasses or contacts',
  'Has a tattoo',
  'Can touch their toes',
  'Has a birthday this month',
  'Drinks coffee every day',
  'Has lived in another country',
  'Is the youngest in their family',
  'Has a green thumb',
  'Can ride a bicycle',
  'Has been camping',
  'Loves to cook',
  'Has flown a kite',
  'Has been to a concert this year',
  'Can whistle',
  'Has a nickname',
  'Has read more than ten books this year',
  'Prefers tea over coffee',
  'Has been on a boat',
  'Knows how to swim',
  'Has seen the northern lights',
  'Works in tech',
  'Has traveled by train',
  'Has won a contest',
  'Has an older sibling',
  'Loves the rain',
  'Has been skiing or snowboarding',
  'Has dyed their hair',
  'Can do a handstand',
  'Is afraid of heights',
  'Has visited a national park',
  'Has a favorite football team',
  'Has baked bread from scratch',
  'Has gone stargazing this year',
  'Is a morning person',
  'Has a collection',
  'Has watched a movie in a theater this month',
  'Is the oldest in their family',
  'Has a birthday in the same month as you',
];

export const normalizeTaskBagText = (text: string): string =>
  text.trim().normalize('NFKC').toLocaleLowerCase('en-US');